include_directories(${CMAKE_CURRENT_LIST_DIR})

if (NOT DEFINED XSTRUCTWIDGET_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/xstructwidget.cmake)
    set(XABSTRACTWIDGETS_SOURCES ${XABSTRACTWIDGETS_SOURCES} ${XSTRUCTWIDGET_SOURCES})
endif()

set(XABSTRACTWIDGETS_SOURCES
    ${XABSTRACTWIDGETS_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/xmainwidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmainwidget.h
)
