include_directories(${CMAKE_CURRENT_LIST_DIR})

if (NOT DEFINED XCOMBOBOXEX_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../../Controls/xcomboboxex.cmake)
    set(XFILEEXPLORERWIDGET_SOURCES ${XFILEEXPLORERWIDGET_SOURCES} ${XCOMBOBOXEX_SOURCES})
endif()
if (NOT DEFINED XFILEINFO_SOURCES)
    add_definitions(-DUSE_DEX)
    add_definitions(-DUSE_PDF)
    add_definitions(-DUSE_ARCHIVE)
    include(${CMAKE_CURRENT_LIST_DIR}/../../XFileInfo/xfileinfo.cmake)
    set(XFILEEXPLORERWIDGET_SOURCES ${XFILEEXPLORERWIDGET_SOURCES} ${XFILEINFO_SOURCES})
endif()
if (NOT DEFINED XSHORTCUTS_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../../XShortcuts/xshortcuts.cmake)
    set(XFILEEXPLORERWIDGET_SOURCES ${XFILEEXPLORERWIDGET_SOURCES} ${XSHORTCUTS_SOURCES})
endif()
if (NOT DEFINED DIALOGWIDGET_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../../FormatDialogs/dialogwidget.cmake)
    set(XFILEEXPLORERWIDGET_SOURCES ${XFILEEXPLORERWIDGET_SOURCES} ${DIALOGWIDGET_SOURCES})
endif()
if (NOT DEFINED XDIALOGPROCESS_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../../FormatDialogs/xdialogprocess.cmake)
    set(XFILEEXPLORERWIDGET_SOURCES ${XFILEEXPLORERWIDGET_SOURCES} ${XDIALOGPROCESS_SOURCES})
endif()

set(XFILEEXPLORERWIDGET_SOURCES
    ${XFILEEXPLORERWIDGET_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/xfilesystemmodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfilesystemmodel.h
    ${CMAKE_CURRENT_LIST_DIR}/xfileexplorerwidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfileexplorerwidget.h
    ${CMAKE_CURRENT_LIST_DIR}/xfileexplorerwidget.ui
)
